logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: tourist
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/tourists/**
        - id: service
          uri: http://localhost:5279/
          predicates:
            - Path=/api/service/**
        - id: raiting
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/rating/**
        - id: trip
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/trip/**
        - id: agency
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/agency/**
        - id: guide
          uri: http://localhost:8083/
          predicates:
            - Path=/api/v1/guide/**
        - id: reservation
          uri: http://localhost:8086/
          predicates:
            - Path=/api/v1/reservation/**

